spring:
  cloud:
    gateway:
      routes:
      - id: DEPARTMENTSERVICE
        uri: lb://DEPARTMENTSERVICE
        predicates:
        - Path=/department/**
        
      - id: EMPLOYEESERVICE
        uri: lb://EMPLOYEESERVICE
        predicates:
        - Path=/employee/**